config/routes.rb
Penntwit::Application.routes.draw do

  get "sessions/new"

  get "users/new"
  match '/signup', :to => 'users#new'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match 'users/:id/profile' => 'users#profile'

  root :to => 'pages#home'

 get "pages/home"

 get "pages/contact"

 get "pages/about"

  resources :messages

  resources :tweets

  resources :users

  resources :sessions, :only => [:new, :create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
	  <li><%= link_to "Show Users", users_path %></li>
	  <li><%= link_to "Show Messages", messages_path %></li>
	  <li><%= link_to "Show Tweets", tweets_path %></li>
      <% if signed_in? %>
      <li><%= link_to "Profile", get_current_user %></li>
      <li><%= link_to "Settings", edit_user_path(get_current_user) %></li>
      <% end %>
      <% if signed_in? %>
      <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
      <% else %>
      <li><%= link_to "Sign in", signin_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PennTwit | <%= @title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag :defaults %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>